name: Build Windows CUDA 12
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@master # 升级到最新版，解决 Node 20 警告
        with:
          cuda: '12.2.0'
          # 使用最新版插件可以尽量避免老版本遇到 GitHub 缓存服务波动时的崩溃

      - name: Configure and Build
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DGGML_CUDA=ON -DGGML_CUDA_FA=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j 4

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-cpp-tq3-windows-cuda
          path: build/bin/Release/*
