name: Build Windows CUDA (Ultimate Standalone)
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CUDA Toolkit 12.5.1
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: '12.5.1' 

      - name: Configure CMake (注入 4070 Ti Super 灵魂！)
        continue-on-error: true
        run: |
          # 核心改动：加入了 -DCMAKE_CUDA_ARCHITECTURES=89，生成纯正的 Ada 架构机器码
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DGGML_CUDA=ON -DGGML_CUDA_FA=ON -DLLAMA_CURL=OFF -DCMAKE_CUDA_ARCHITECTURES=89 -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release -j 4

      - name: Bundle NVIDIA CUDA DLLs
        continue-on-error: true
        run: |
          $cuda_bin = "${{ steps.cuda-toolkit.outputs.CUDA_PATH }}\bin"
          Copy-Item "$cuda_bin\cudart64_*.dll" -Destination "build\bin\Release\"
          Copy-Item "$cuda_bin\cublas64_*.dll" -Destination "build\bin\Release\"
          Copy-Item "$cuda_bin\cublasLt64_*.dll" -Destination "build\bin\Release\"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-cpp-tq3-windows-cuda-ULTIMATE
          path: build/bin/Release/
